apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ac
  name: account-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ac
  template:
    metadata:
      labels:
        app: ac
    spec:
      containers:
      - name: ac-image
        image: 398443246513.dkr.ecr.ap-south-1.amazonaws.com/off-ecr:feature1
        ports:
        - containerPort: 2222
---
apiVersion: v1
kind: Service
metadata:
  name: Service
spec:
  selector:
  	app: ac
  type: NodePort
  ports:
  - port: 80
    targetPort: 2222
    nodePort: 30036
