apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-services
  labels:
    app: ac
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ac
  template:
    metadata:
      labels:
        app: ac
    spec:
      containers:
      - name: acc-ser
        image: 398443246513.dkr.ecr.ap-south-1.amazonaws.com/new-ecr:feature
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: Service
spec:
  selector:
  	app: ms
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30036

