apiVersion: apps/v1
kind: Deployment
metadata:
  name: acc-dep
spec:
  selector:
    matchLabels:
      app: account
  replicas: 2
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
      - name: my-imag
        image: 398443246513.dkr.ecr.ap-south-1.amazonaws.com/new-ecr:feature
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: Service
spec:
  selector:
  	app: ms
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30036


