apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deploy
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: account-ser
        image: 398443246513.dkr.ecr.ap-south-1.amazonaws.com/new-ecr:feature
        ports:
        - containerPort: 8080


---

apiVersion: v1
kind: Service
metadata:
  name: Service
spec:
  selector:
  	app: ms
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30036


