apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ac
    name: account-services
  spec:
    replicas: 1
    selector: null
    matchLabels:
      app: ac
  template:
    metadata:
      labels:
        app: ac
    spec:
      containers:
        - name: ac-image
          image: 398443246513.dkr.ecr.ap-south-1.amazonaws.com/off-ecr:feature1
          imagePullPolicy: Always
          ports:
            - containerPort: 2222
              name: http
              protocol: TCP

# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  name: Service
spec:
  selector:
  	app: ac
  type: NodePort
  ports:
  - port: 80
    targetPort: 2222
    nodePort: 30036
