  pipeline {
   
    agent any

    stages {

        stage('Clone repository') { 
            steps { 
                script{
                checkout scm
                }
            }
        }

        stage('branch show') { 
            steps { 
               sh 'chmod +x getbranch.sh'
               sh './getbranch.sh'
             
            }
        }

    }
}

