pipeline {
   
    agent any

    stages {

        stage('Clone repository') { 
            steps { 
                script{
                checkout scm
                }
            }
        }

        stage('branch show') { 
            steps { 
               script{
                  image_version = env.${GIT_BRANCH}.replace("/", "-")
               
            }
        }
    }
      stage('branch show') { 
            steps { 
               sh 'echo "${image_version}"' 
       
}
      }
    }
}
