pipeline {
   
    agent any

    stages {

        stage('Clone repository') { 
            steps { 
                script{
                checkout scm
                }
            }
        }
        stage('Build Jar') {
            steps {
                sh 'pwd'
                sh 'ls -la'
                dir('account-service'){
                sh 'mvn clean package'
                }
            }

        }
        stage('Docker Image Build') {
            steps {
                dir('account-service'){
                sh 'docker build -t off-ecr .'
                }
            }
        }

    }

}
